# This workflos is based on the default python app one, available at
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and lint

on:
  push:
    branches-ignore:
    - skipci/**
  pull_request:
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v2

    - name: Read devbox Python version
      run: |
        jq '.packages.["python-full"].version | "PYTHON_VERSION=\(.)"' \
            --raw-output devbox.json >> "$GITHUB_ENV"

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.15"

    - name: Test
      run: uv run test --verbose
